name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - uses: actions/github-script@0.3.0
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          script: |
            const core = require("@actions/core");
            const { readFileSync } = require("fs");
            const content = await readFileSync('CHANGELOG.md', 'utf8');
            core.setOutput('content', content);
          id: release_info

      - name: Printout release notes
        run: >
          curl --request POST \
            --url https://be.fortress.d.foundation/webhook/basecamp/changelog-message \
            --header 'Content-Type: application/json' \
            --data '{
              "project": "WEBUILD",
              "message": "${{ steps.release_info.outputs.content }}"
            }'
