name: Release on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Printout release notes
        run: echo $(steps.extract-release-notes.outputs.release_notes) for $(github.ref)
